<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-42PTP2V" failures="0" tests="4" name="waesqa.DeleteUserTest" time="0.992" errors="1" timestamp="2019-10-07T23:21:47 ART" skipped="3">
  <testcase classname="waesqa.DeleteUserTest" name="deleteInvalidAuth" time="0.000">
    <skipped/>
  </testcase> <!-- deleteInvalidAuth -->
  <testcase classname="waesqa.DeleteUserTest" name="beforeClass" time="0.991">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at utils.WaesHeroesAPIs.reportLog(WaesHeroesAPIs.java:161)
at utils.WaesHeroesAPIs.postSignUp(WaesHeroesAPIs.java:100)
at waesqa.DeleteUserTest.beforeClass(DeleteUserTest.java:33)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:340)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:294)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:176)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
    </error>
  </testcase> <!-- beforeClass -->
  <testcase classname="waesqa.DeleteUserTest" name="deleteNonExistingUser" time="0.000">
    <skipped/>
  </testcase> <!-- deleteNonExistingUser -->
  <testcase classname="waesqa.DeleteUserTest" name="deletePositive" time="0.001">
    <skipped/>
  </testcase> <!-- deletePositive -->
</testsuite> <!-- waesqa.DeleteUserTest -->
